defaults: 
  - visualization: eval

num_workers: 0
batch_size: 1
cuda: 0
weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
#TO ADAPT

checkpoint_dir: ""
precompute_multi_scale: True # Compute multiscate features on cpu for faster training / inference
enable_dropout: False
voting_runs: 1
data: 
  #TO ADAPT

  fold: ['']

tracker_options: # Extra options for the tracker
  full_res: True
  make_submission: True
  ply_output: "vote1regular.ply"

hydra:
  run:
    dir: ${checkpoint_dir}/eval/${now:%Y-%m-%d_%H-%M-%S}


